# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ZedCamTest.xdc

# Block Designs: bd/bd/bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd || ORIG_REF_NAME==bd}]

# IP: bd/bd/ip/bd_processing_system7_0_0_1/bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_processing_system7_0_0 || ORIG_REF_NAME==bd_processing_system7_0_0}]

# IP: bd/bd/ip/bd_processing_system7_0_axi_periph_0_1/bd_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==bd_processing_system7_0_axi_periph_0}]

# IP: bd/bd/ip/bd_rst_processing_system7_0_100M_0_1/bd_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==bd_rst_processing_system7_0_100M_0}]

# IP: bd/bd/ip/bd_ZedCamAXI_0_0/bd_ZedCamAXI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ZedCamAXI_0_0 || ORIG_REF_NAME==bd_ZedCamAXI_0_0}]

# IP: bd/bd/ip/bd_ZedCamAXI_0_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0}]

# IP: bd/bd/ip/bd_ZedCamAXI_0_0/src/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0}]

# IP: bd/bd/ip/bd_xbar_1/bd_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_xbar_1 || ORIG_REF_NAME==bd_xbar_1}]

# IP: bd/bd/ip/bd_auto_pc_0/bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_auto_pc_0 || ORIG_REF_NAME==bd_auto_pc_0}]

# IP: bd/bd/ip/bd_auto_pc_1/bd_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_auto_pc_1 || ORIG_REF_NAME==bd_auto_pc_1}]

# XDC: bd/bd/ip/bd_processing_system7_0_0_1/bd_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_processing_system7_0_0 || ORIG_REF_NAME==bd_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/bd/ip/bd_rst_processing_system7_0_100M_0_1/bd_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==bd_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/bd/ip/bd_rst_processing_system7_0_100M_0_1/bd_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==bd_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/bd/ip/bd_rst_processing_system7_0_100M_0_1/bd_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/bd/ip/bd_ZedCamAXI_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: bd/bd/ip/bd_ZedCamAXI_0_0/src/clk_wiz_0/clk_wiz_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0}] {/inst }]/inst ]]

# XDC: bd/bd/ip/bd_ZedCamAXI_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# XDC: bd/bd/ip/bd_xbar_1/bd_xbar_1_ooc.xdc

# XDC: bd/bd/ip/bd_auto_pc_0/bd_auto_pc_0_ooc.xdc

# XDC: bd/bd/ip/bd_auto_pc_1/bd_auto_pc_1_ooc.xdc

# XDC: bd/bd/bd_ooc.xdc
