# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ZedCamTest.xdc

# IP: ip/processing_system7_0/processing_system7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processing_system7_0 || ORIG_REF_NAME==processing_system7_0}]

# XDC: ip/processing_system7_0/processing_system7_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==processing_system7_0 || ORIG_REF_NAME==processing_system7_0}] {/inst }]/inst ]]
