# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/georges/Documents/GitHub/MQP/ZedCamTest/ZedCamTest.cache/wt [current_project]
set_property parent.project_path C:/Users/georges/Documents/GitHub/MQP/ZedCamTest/ZedCamTest.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files -quiet C:/Users/georges/Documents/GitHub/MQP/ZedCamTest/ZedCamTest.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files C:/Users/georges/Documents/GitHub/MQP/ZedCamTest/ZedCamTest.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
add_files -quiet c:/Users/georges/Documents/GitHub/MQP/ZedCamTest/ZedCamTest.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files c:/Users/georges/Documents/GitHub/MQP/ZedCamTest/ZedCamTest.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/georges/Documents/GitHub/MQP/ZedCamTest/ZedCamTest.srcs/sources_1/new/debounce.v
  C:/Users/georges/Documents/GitHub/MQP/ZedCamTest/ZedCamTest.srcs/sources_1/new/clk_divs.v
  C:/Users/georges/Documents/GitHub/MQP/ZedCamTest/ZedCamTest.srcs/sources_1/new/imgbuf.v
  C:/Users/georges/Documents/GitHub/MQP/ZedCamTest/ZedCamTest.srcs/sources_1/new/ZedCamTest_top.v
}
read_vhdl -library xil_defaultlib C:/Users/georges/Documents/GitHub/MQP/ZedCamTest/ZedCamTest.srcs/sources_1/new/vga_controller_640_60.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/georges/Documents/GitHub/MQP/ZedCamTest/ZedCamTest.srcs/constrs_1/new/ZedCamTest.xdc
set_property used_in_implementation false [get_files C:/Users/georges/Documents/GitHub/MQP/ZedCamTest/ZedCamTest.srcs/constrs_1/new/ZedCamTest.xdc]


synth_design -top ZedCamTest_top -part xc7z020clg484-1


write_checkpoint -force -noxdef ZedCamTest_top.dcp

catch { report_utilization -file ZedCamTest_top_utilization_synth.rpt -pb ZedCamTest_top_utilization_synth.pb }
