# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/georges/Documents/GitHub/MQP/InOut/InOut.cache/wt [current_project]
set_property parent.project_path C:/Users/georges/Documents/GitHub/MQP/InOut/InOut.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
read_verilog -library xil_defaultlib C:/Users/georges/Documents/GitHub/MQP/InOut/InOut.srcs/sources_1/new/InOut.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/georges/Documents/GitHub/MQP/InOut/InOut.srcs/constrs_1/new/InOut.xdc
set_property used_in_implementation false [get_files C:/Users/georges/Documents/GitHub/MQP/InOut/InOut.srcs/constrs_1/new/InOut.xdc]


synth_design -top InOut -part xc7z020clg484-1


write_checkpoint -force -noxdef InOut.dcp

catch { report_utilization -file InOut_utilization_synth.rpt -pb InOut_utilization_synth.pb }
