# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/fuck_mqp/fuck_mqp.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fuck_mqp || ORIG_REF_NAME==fuck_mqp}]

# IP: bd/fuck_mqp/ip/fuck_mqp_processing_system7_0_0/fuck_mqp_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fuck_mqp_processing_system7_0_0 || ORIG_REF_NAME==fuck_mqp_processing_system7_0_0}]

# IP: bd/fuck_mqp/ip/fuck_mqp_axi_gpio_0_2/fuck_mqp_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fuck_mqp_axi_gpio_0_2 || ORIG_REF_NAME==fuck_mqp_axi_gpio_0_2}]

# IP: bd/fuck_mqp/ip/fuck_mqp_processing_system7_0_axi_periph_2/fuck_mqp_processing_system7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fuck_mqp_processing_system7_0_axi_periph_2 || ORIG_REF_NAME==fuck_mqp_processing_system7_0_axi_periph_2}]

# IP: bd/fuck_mqp/ip/fuck_mqp_rst_processing_system7_0_100M_2/fuck_mqp_rst_processing_system7_0_100M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fuck_mqp_rst_processing_system7_0_100M_2 || ORIG_REF_NAME==fuck_mqp_rst_processing_system7_0_100M_2}]

# IP: bd/fuck_mqp/ip/fuck_mqp_auto_pc_0/fuck_mqp_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fuck_mqp_auto_pc_0 || ORIG_REF_NAME==fuck_mqp_auto_pc_0}]

# XDC: bd/fuck_mqp/ip/fuck_mqp_processing_system7_0_0/fuck_mqp_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fuck_mqp_processing_system7_0_0 || ORIG_REF_NAME==fuck_mqp_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/fuck_mqp/ip/fuck_mqp_axi_gpio_0_2/fuck_mqp_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fuck_mqp_axi_gpio_0_2 || ORIG_REF_NAME==fuck_mqp_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/fuck_mqp/ip/fuck_mqp_axi_gpio_0_2/fuck_mqp_axi_gpio_0_2_ooc.xdc

# XDC: bd/fuck_mqp/ip/fuck_mqp_axi_gpio_0_2/fuck_mqp_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fuck_mqp_axi_gpio_0_2 || ORIG_REF_NAME==fuck_mqp_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/fuck_mqp/ip/fuck_mqp_rst_processing_system7_0_100M_2/fuck_mqp_rst_processing_system7_0_100M_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fuck_mqp_rst_processing_system7_0_100M_2 || ORIG_REF_NAME==fuck_mqp_rst_processing_system7_0_100M_2}] {/U0 }]/U0 ]]

# XDC: bd/fuck_mqp/ip/fuck_mqp_rst_processing_system7_0_100M_2/fuck_mqp_rst_processing_system7_0_100M_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fuck_mqp_rst_processing_system7_0_100M_2 || ORIG_REF_NAME==fuck_mqp_rst_processing_system7_0_100M_2}] {/U0 }]/U0 ]]

# XDC: bd/fuck_mqp/ip/fuck_mqp_rst_processing_system7_0_100M_2/fuck_mqp_rst_processing_system7_0_100M_2_ooc.xdc

# XDC: bd/fuck_mqp/ip/fuck_mqp_auto_pc_0/fuck_mqp_auto_pc_0_ooc.xdc

# XDC: bd/fuck_mqp/fuck_mqp_ooc.xdc
