# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/John/Documents/GitHub/MQP/killme/killme.cache/wt [current_project]
set_property parent.project_path C:/Users/John/Documents/GitHub/MQP/killme/killme.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files C:/Users/John/Documents/GitHub/MQP/killme/killme.srcs/sources_1/bd/fuck_mqp/fuck_mqp.bd
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/GitHub/MQP/killme/killme.srcs/sources_1/bd/fuck_mqp/ip/fuck_mqp_processing_system7_0_0/fuck_mqp_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/GitHub/MQP/killme/killme.srcs/sources_1/bd/fuck_mqp/ip/fuck_mqp_axi_gpio_0_2/fuck_mqp_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/GitHub/MQP/killme/killme.srcs/sources_1/bd/fuck_mqp/ip/fuck_mqp_axi_gpio_0_2/fuck_mqp_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/GitHub/MQP/killme/killme.srcs/sources_1/bd/fuck_mqp/ip/fuck_mqp_axi_gpio_0_2/fuck_mqp_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/GitHub/MQP/killme/killme.srcs/sources_1/bd/fuck_mqp/ip/fuck_mqp_rst_processing_system7_0_100M_2/fuck_mqp_rst_processing_system7_0_100M_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/GitHub/MQP/killme/killme.srcs/sources_1/bd/fuck_mqp/ip/fuck_mqp_rst_processing_system7_0_100M_2/fuck_mqp_rst_processing_system7_0_100M_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/GitHub/MQP/killme/killme.srcs/sources_1/bd/fuck_mqp/ip/fuck_mqp_rst_processing_system7_0_100M_2/fuck_mqp_rst_processing_system7_0_100M_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/GitHub/MQP/killme/killme.srcs/sources_1/bd/fuck_mqp/ip/fuck_mqp_auto_pc_0/fuck_mqp_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/John/Documents/GitHub/MQP/killme/killme.srcs/sources_1/bd/fuck_mqp/fuck_mqp_ooc.xdc]
set_property is_locked true [get_files C:/Users/John/Documents/GitHub/MQP/killme/killme.srcs/sources_1/bd/fuck_mqp/fuck_mqp.bd]

read_verilog -library xil_defaultlib C:/Users/John/Documents/GitHub/MQP/killme/killme.srcs/sources_1/imports/hdl/fuck_mqp_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top fuck_mqp_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef fuck_mqp_wrapper.dcp

catch { report_utilization -file fuck_mqp_wrapper_utilization_synth.rpt -pb fuck_mqp_wrapper_utilization_synth.pb }
