# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/John/Documents/GitHub/MQP/IMU/IMU.srcs/sources_1/ip/div_gen_0/div_gen_0.xci
# IP: The module: 'div_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/John/Documents/GitHub/MQP/IMU/IMU.srcs/sources_1/ip/div_gen_0/div_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/John/Documents/GitHub/MQP/IMU/IMU.srcs/sources_1/ip/div_gen_0/div_gen_0.xci
# IP: The module: 'div_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/John/Documents/GitHub/MQP/IMU/IMU.srcs/sources_1/ip/div_gen_0/div_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
