webtalk_init -webtalk_dir C:\\Users\\John\\Documents\\GitHub\\MQP\\rangefinder_blocks\\rangefinder_blocks.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Nov 20 18:13:23 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a6atpeuqmtop8gsi4aqbn72oer" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_49" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "49" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1479353578246" -context "sdk\\\\hardware/1479353578246"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1479353578246"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1479353578246"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.2" -context "sdk\\\\hardware/1479353578246"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1479353578246"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1479353578246"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1479353578246"
webtalk_add_data -client sdk -key uid -value "1479353644593" -context "sdk\\\\bsp/1479353644593"
webtalk_add_data -client sdk -key hwid -value "1479353578246" -context "sdk\\\\bsp/1479353644593"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1479353644593"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1479353644593"
webtalk_add_data -client sdk -key uid -value "1479353664997" -context "sdk\\\\application/1479353664997"
webtalk_add_data -client sdk -key hwid -value "1479353578246" -context "sdk\\\\application/1479353664997"
webtalk_add_data -client sdk -key bspid -value "1479353644593" -context "sdk\\\\application/1479353664997"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1479353664997"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1479353664997"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1479353664997"
webtalk_add_data -client sdk -key uid -value "1479353852971" -context "sdk\\\\bsp/1479353852971"
webtalk_add_data -client sdk -key hwid -value "1479353578246" -context "sdk\\\\bsp/1479353852971"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1479353852971"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1479353852971"
webtalk_add_data -client sdk -key uid -value "1479353856656" -context "sdk\\\\application/1479353856656"
webtalk_add_data -client sdk -key hwid -value "1479353578246" -context "sdk\\\\application/1479353856656"
webtalk_add_data -client sdk -key bspid -value "1479353852971" -context "sdk\\\\application/1479353856656"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1479353856656"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1479353856656"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1479353856656"
webtalk_transmit -clientid 94224554 -regid "" -xml C:\\Users\\John\\Documents\\GitHub\\MQP\\rangefinder_blocks\\rangefinder_blocks.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\John\\Documents\\GitHub\\MQP\\rangefinder_blocks\\rangefinder_blocks.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\John\\Documents\\GitHub\\MQP\\rangefinder_blocks\\rangefinder_blocks.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
