# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/idkman/idkman.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==idkman || ORIG_REF_NAME==idkman}]

# IP: bd/idkman/ip/idkman_processing_system7_0_0/idkman_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==idkman_processing_system7_0_0 || ORIG_REF_NAME==idkman_processing_system7_0_0}]

# IP: bd/idkman/ip/idkman_axi_gpio_0_0/idkman_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==idkman_axi_gpio_0_0 || ORIG_REF_NAME==idkman_axi_gpio_0_0}]

# IP: bd/idkman/ip/idkman_processing_system7_0_axi_periph_0/idkman_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==idkman_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==idkman_processing_system7_0_axi_periph_0}]

# IP: bd/idkman/ip/idkman_rst_processing_system7_0_100M_0/idkman_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==idkman_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==idkman_rst_processing_system7_0_100M_0}]

# IP: bd/idkman/ip/idkman_auto_pc_0/idkman_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==idkman_auto_pc_0 || ORIG_REF_NAME==idkman_auto_pc_0}]

# XDC: bd/idkman/ip/idkman_processing_system7_0_0/idkman_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==idkman_processing_system7_0_0 || ORIG_REF_NAME==idkman_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/idkman/ip/idkman_axi_gpio_0_0/idkman_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==idkman_axi_gpio_0_0 || ORIG_REF_NAME==idkman_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/idkman/ip/idkman_axi_gpio_0_0/idkman_axi_gpio_0_0_ooc.xdc

# XDC: bd/idkman/ip/idkman_axi_gpio_0_0/idkman_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==idkman_axi_gpio_0_0 || ORIG_REF_NAME==idkman_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/idkman/ip/idkman_rst_processing_system7_0_100M_0/idkman_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==idkman_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==idkman_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/idkman/ip/idkman_rst_processing_system7_0_100M_0/idkman_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==idkman_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==idkman_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/idkman/ip/idkman_rst_processing_system7_0_100M_0/idkman_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/idkman/ip/idkman_auto_pc_0/idkman_auto_pc_0_ooc.xdc

# XDC: bd/idkman/idkman_ooc.xdc
