#!/bin/bash -f
# Vivado (TM) v2016.2 (64-bit)
#
# Filename    : axi_traffic_gen_0.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Sep 06 11:05:08 -0400 2016
# IP Build 1577682 on Fri Jun  3 12:00:54 MDT 2016 
#
# usage: axi_traffic_gen_0.sh [-help]
# usage: axi_traffic_gen_0.sh [-lib_map_path]
# usage: axi_traffic_gen_0.sh [-noclean_files]
# usage: axi_traffic_gen_0.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'axi_traffic_gen_0.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64 -timescale=1ps/1ps"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm dist_mem_gen_v8_0_10 blk_mem_gen_v8_3_3 lib_bmg_v1_0_5 lib_cdc_v1_0_2 axi_traffic_gen_v2_0_10)

# Simulation root library directory
sim_lib_dir="vcs"

# Script info
echo -e "axi_traffic_gen_0.sh - Script generated by export_simulation (Vivado v2016.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog" +incdir+"$ref_dir/../../../../axi_uartlite_0_example.srcs/sources_1/ip/axi_traffic_gen_0/hdl/src/verilog" \
    "C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work dist_mem_gen_v8_0_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog" +incdir+"$ref_dir/../../../../axi_uartlite_0_example.srcs/sources_1/ip/axi_traffic_gen_0/hdl/src/verilog" \
    "$ref_dir/../../../ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_3_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog" +incdir+"$ref_dir/../../../../axi_uartlite_0_example.srcs/sources_1/ip/axi_traffic_gen_0/hdl/src/verilog" \
    "$ref_dir/../../../ipstatic/blk_mem_gen_v8_3_3/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_5 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/lib_bmg_v1_0_5/hdl/src/vhdl/blk_mem_gen_wrapper.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/lib_cdc_v1_0_2/hdl/src/vhdl/cdc_sync.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_traffic_gen_v2_0_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog" +incdir+"$ref_dir/../../../../axi_uartlite_0_example.srcs/sources_1/ip/axi_traffic_gen_0/hdl/src/verilog" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_asynch_rst_ff.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_slvram_v7.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_regslice.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_traffic_gen_v2_0_10 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/vhdl/axi_traffic_gen_v2_0_bmg_wrap.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_traffic_gen_v2_0_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog" +incdir+"$ref_dir/../../../../axi_uartlite_0_example.srcs/sources_1/ip/axi_traffic_gen_0/hdl/src/verilog" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_inferram.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_randgen.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_id_track.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_ex_fifo.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_cmdram.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_addrgen.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_s_w_channel.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_s_r_channel.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_sharedram_wrap.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_registers.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_paramram_wrap.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_paramram_64_wrap.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_addrram_wrap.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_m_w_channel.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_m_r_channel.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_cmdram_wrap.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_static_regblk.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_static_cmdgen.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_static_mrdwr.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_static_top.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_slave_only_top.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_basic_n_full_top.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_axis_fifo.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_streaming_top.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_systeminit_dmg.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_systeminit_mrdwr.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_systeminit_top.v" \
    "$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog/axi_traffic_gen_v2_0_top.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../ipstatic/axi_traffic_gen_v2_0_10/hdl/src/verilog" +incdir+"$ref_dir/../../../../axi_uartlite_0_example.srcs/sources_1/ip/axi_traffic_gen_0/hdl/src/verilog" \
    "$ref_dir/../../../../axi_uartlite_0_example.srcs/sources_1/ip/axi_traffic_gen_0/sim/axi_traffic_gen_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.axi_traffic_gen_0 xil_defaultlib.glbl -o axi_traffic_gen_0_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./axi_traffic_gen_0_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./axi_traffic_gen_0.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key axi_traffic_gen_0_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc axi_traffic_gen_0_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./axi_traffic_gen_0.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: axi_traffic_gen_0.sh [-help]\n\
Usage: axi_traffic_gen_0.sh [-lib_map_path]\n\
Usage: axi_traffic_gen_0.sh [-reset_run]\n\
Usage: axi_traffic_gen_0.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
