create_clock -period 10.000 -name clock -add [get_ports fpga_clk]
set_property PACKAGE_PIN Y9 [get_ports fpga_clk]
set_property IOSTANDARD LVCMOS33 [get_ports fpga_clk]


set_property PACKAGE_PIN P16 [get_ports reset]
set_property PACKAGE_PIN R18 [get_ports button]

set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports button]

set_property PACKAGE_PIN V7 [get_ports cs_nAG]
set_property PACKAGE_PIN V4 [get_ports sclk]
set_property PACKAGE_PIN W7 [get_ports mosi]
set_property PACKAGE_PIN V5 [get_ports miso]
set_property PACKAGE_PIN U5 [get_ports cs_nALT]
set_property PACKAGE_PIN U6 [get_ports cs_nM]

set_property PACKAGE_PIN U14 [get_ports led[7]]
set_property PACKAGE_PIN U19 [get_ports led[6]]
set_property PACKAGE_PIN W22 [get_ports led[5]]
set_property PACKAGE_PIN V22 [get_ports led[4]]
set_property PACKAGE_PIN U21 [get_ports led[3]]
set_property PACKAGE_PIN U22 [get_ports led[2]]
set_property PACKAGE_PIN T21 [get_ports led[1]]
set_property PACKAGE_PIN T22 [get_ports led[0]]

set_property IOSTANDARD LVCMOS33 [get_ports cs_nAG]
set_property IOSTANDARD LVCMOS33 [get_ports sclk]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports miso]
set_property IOSTANDARD LVCMOS33 [get_ports cs_nALT]
set_property IOSTANDARD LVCMOS33 [get_ports cs_nM]

set_property IOSTANDARD LVCMOS33 [get_ports led[7]]
set_property IOSTANDARD LVCMOS33 [get_ports led[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[0]]