# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/IMU_bd/IMU_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IMU_bd || ORIG_REF_NAME==IMU_bd}]

# IP: bd/IMU_bd/ip/IMU_bd_processing_system7_0_0/IMU_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IMU_bd_processing_system7_0_0 || ORIG_REF_NAME==IMU_bd_processing_system7_0_0}]

# XDC: bd/IMU_bd/ip/IMU_bd_processing_system7_0_0/IMU_bd_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IMU_bd_processing_system7_0_0 || ORIG_REF_NAME==IMU_bd_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/IMU_bd/IMU_bd_ooc.xdc
