create_clock -period 10.000 -name clock -add [get_ports fpga_clk]
set_property PACKAGE_PIN Y9 [get_ports fpga_clk]
set_property IOSTANDARD LVCMOS33 [get_ports fpga_clk]

set_property PACKAGE_PIN P16 [get_ports reset]

set_property PACKAGE_PIN V18 [get_ports {rgb[11]}]
set_property PACKAGE_PIN V19 [get_ports {rgb[10]}]
set_property PACKAGE_PIN U20 [get_ports {rgb[9]}]
set_property PACKAGE_PIN V20 [get_ports {rgb[8]}]
set_property PACKAGE_PIN AA21 [get_ports {rgb[7]}]
set_property PACKAGE_PIN AB21 [get_ports {rgb[6]}]
set_property PACKAGE_PIN AA22 [get_ports {rgb[5]}]
set_property PACKAGE_PIN AB22 [get_ports {rgb[4]}]
set_property PACKAGE_PIN AB19 [get_ports {rgb[3]}]
set_property PACKAGE_PIN AB20 [get_ports {rgb[2]}]
set_property PACKAGE_PIN Y20 [get_ports {rgb[1]}]
set_property PACKAGE_PIN Y21 [get_ports {rgb[0]}]
set_property PACKAGE_PIN AA19 [get_ports hsync]
set_property PACKAGE_PIN Y19 [get_ports vsync]

set_property IOSTANDARD LVCMOS18 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports {rgb[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]


