# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.cache/wt [current_project]
set_property parent.project_path C:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  c:/Users/John/Documents/GitHub/MQP/ip_repo/nu_nu_rangefinder_vga_1.0
  c:/Users/John/Documents/GitHub/MQP/ip_repo/nu_rangefinder_vga_1.0
  c:/Users/John/Documents/GitHub/MQP/ip_repo/rangefinder_vga_1.0
  c:/Users/John/Documents/GitHub/MQP/ip_repo/new_rangefinder_vga_1.0
  c:/Users/John/Documents/GitHub/MQP/ip_repo/rangefinder_vga_1.0
} [current_project]
add_files C:/Users/John/Desktop/MQP/backups/coord1.coe
add_files C:/Users/John/Desktop/MQP/backups/coord2.coe
add_files C:/Users/John/Desktop/MQP/backups/vga_map.coe
add_files -quiet C:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/sources_1/bd/design_1/design_1.dcp
set_property used_in_implementation false [get_files C:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/sources_1/bd/design_1/design_1.dcp]
read_verilog -library xil_defaultlib C:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/constrs_1/new/mqp.xdc
set_property used_in_implementation false [get_files C:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/constrs_1/new/mqp.xdc]


synth_design -top design_1_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
