# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.cache/wt [current_project]
set_property parent.project_path C:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  c:/Users/John/Documents/GitHub/MQP/ip_repo/nu_nu_rangefinder_vga_1.0
  c:/Users/John/Documents/GitHub/MQP/ip_repo/nu_rangefinder_vga_1.0
  c:/Users/John/Documents/GitHub/MQP/ip_repo/rangefinder_vga_1.0
  c:/Users/John/Documents/GitHub/MQP/ip_repo/new_rangefinder_vga_1.0
  c:/Users/John/Documents/GitHub/MQP/ip_repo/rangefinder_vga_1.0
} [current_project]
add_files C:/Users/John/Desktop/MQP/backups/coord1.coe
add_files C:/Users/John/Desktop/MQP/backups/coord2.coe
add_files C:/Users/John/Desktop/MQP/backups/vga_map.coe
add_files C:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/sources_1/bd/design_1/ip/design_1_nu_nu_rangefinder_vga_0_0/src/clk_wiz_0_1/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/sources_1/bd/design_1/ip/design_1_nu_nu_rangefinder_vga_0_0/src/clk_wiz_0_1/clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_1/design_1_blk_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_1_0/design_1_blk_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_2_0/design_1_blk_mem_gen_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files C:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib C:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/constrs_1/new/mqp.xdc
set_property used_in_implementation false [get_files C:/Users/John/Documents/GitHub/MQP/rangefinder_blocks/rangefinder_blocks.srcs/constrs_1/new/mqp.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
