set_property SRC_FILE_INFO {cfile:c:/Users/georges/Documents/GitHub/MQP/ZedCamTest/ZedCamTest.srcs/sources_1/ip/processing_system7_0/processing_system7_0.xdc rfile:../../../ZedCamTest.srcs/sources_1/ip/processing_system7_0/processing_system7_0.xdc id:1 order:EARLY scoped_inst:ps/inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/georges/Documents/GitHub/MQP/ZedCamTest/ZedCamTest.srcs/constrs_1/new/ZedCamTest.xdc rfile:../../../ZedCamTest.srcs/constrs_1/new/ZedCamTest.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.6
set_property src_info {type:SCOPED_XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C12" [get_ports "MIO[53]"]
set_property src_info {type:SCOPED_XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D10" [get_ports "MIO[52]"]
set_property src_info {type:SCOPED_XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C10" [get_ports "MIO[51]"]
set_property src_info {type:SCOPED_XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D13" [get_ports "MIO[50]"]
set_property src_info {type:SCOPED_XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C14" [get_ports "MIO[49]"]
set_property src_info {type:SCOPED_XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D11" [get_ports "MIO[48]"]
set_property src_info {type:SCOPED_XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B10" [get_ports "MIO[47]"]
set_property src_info {type:SCOPED_XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D12" [get_ports "MIO[46]"]
set_property src_info {type:SCOPED_XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B9" [get_ports "MIO[45]"]
set_property src_info {type:SCOPED_XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E13" [get_ports "MIO[44]"]
set_property src_info {type:SCOPED_XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B11" [get_ports "MIO[43]"]
set_property src_info {type:SCOPED_XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D8" [get_ports "MIO[42]"]
set_property src_info {type:SCOPED_XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C8" [get_ports "MIO[41]"]
set_property src_info {type:SCOPED_XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E14" [get_ports "MIO[40]"]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C13" [get_ports "MIO[39]"]
set_property src_info {type:SCOPED_XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F13" [get_ports "MIO[38]"]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B14" [get_ports "MIO[37]"]
set_property src_info {type:SCOPED_XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A9" [get_ports "MIO[36]"]
set_property src_info {type:SCOPED_XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F14" [get_ports "MIO[35]"]
set_property src_info {type:SCOPED_XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B12" [get_ports "MIO[34]"]
set_property src_info {type:SCOPED_XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G13" [get_ports "MIO[33]"]
set_property src_info {type:SCOPED_XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C7" [get_ports "MIO[32]"]
set_property src_info {type:SCOPED_XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F9" [get_ports "MIO[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A11" [get_ports "MIO[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E8" [get_ports "MIO[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A12" [get_ports "MIO[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D7" [get_ports "MIO[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A13" [get_ports "MIO[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F12" [get_ports "MIO[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B7" [get_ports "MIO[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E11" [get_ports "MIO[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A14" [get_ports "MIO[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F11" [get_ports "MIO[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A8" [get_ports "MIO[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E10" [get_ports "MIO[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A7" [get_ports "MIO[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E9" [get_ports "MIO[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D6" [get_ports "MIO[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E6" [get_ports "MIO[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B6" [get_ports "MIO[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A6" [get_ports "MIO[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C5" [get_ports "MIO[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B4" [get_ports "MIO[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G7" [get_ports "MIO[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C4" [get_ports "MIO[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E5" [get_ports "MIO[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D5" [get_ports "MIO[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A4" [get_ports "MIO[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A3" [get_ports "MIO[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E4" [get_ports "MIO[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F6" [get_ports "MIO[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A2" [get_ports "MIO[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A1" [get_ports "MIO[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G6" [get_ports "MIO[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_VRP"]
set_property src_info {type:SCOPED_XDC file:1 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N7" [get_ports "DDR_VRP"]
set_property src_info {type:SCOPED_XDC file:1 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_VRP"]
set_property src_info {type:SCOPED_XDC file:1 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_VRP"]
set_property src_info {type:SCOPED_XDC file:1 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_VRN"]
set_property src_info {type:SCOPED_XDC file:1 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M7" [get_ports "DDR_VRN"]
set_property src_info {type:SCOPED_XDC file:1 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_VRN"]
set_property src_info {type:SCOPED_XDC file:1 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_VRN"]
set_property src_info {type:SCOPED_XDC file:1 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_WEB"]
set_property src_info {type:SCOPED_XDC file:1 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R4" [get_ports "DDR_WEB"]
set_property src_info {type:SCOPED_XDC file:1 line:410 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_WEB"]
set_property src_info {type:SCOPED_XDC file:1 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_WEB"]
set_property src_info {type:SCOPED_XDC file:1 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_RAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R5" [get_ports "DDR_RAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_RAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:415 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_RAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_ODT"]
set_property src_info {type:SCOPED_XDC file:1 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P5" [get_ports "DDR_ODT"]
set_property src_info {type:SCOPED_XDC file:1 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_ODT"]
set_property src_info {type:SCOPED_XDC file:1 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_ODT"]
set_property src_info {type:SCOPED_XDC file:1 line:420 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_DRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F3" [get_ports "DDR_DRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "DIFF_SSTL15_T_DCI" [get_ports "DDR_DQS[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V2" [get_ports "DDR_DQS[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:426 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQS[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQS[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "DIFF_SSTL15_T_DCI" [get_ports "DDR_DQS[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N2" [get_ports "DDR_DQS[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQS[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQS[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "DIFF_SSTL15_T_DCI" [get_ports "DDR_DQS[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H2" [get_ports "DDR_DQS[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQS[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQS[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "DIFF_SSTL15_T_DCI" [get_ports "DDR_DQS[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C2" [get_ports "DDR_DQS[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQS[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQS[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "DIFF_SSTL15_T_DCI" [get_ports "DDR_DQS_n[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W2" [get_ports "DDR_DQS_n[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQS_n[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQS_n[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "DIFF_SSTL15_T_DCI" [get_ports "DDR_DQS_n[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P2" [get_ports "DDR_DQS_n[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQS_n[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQS_n[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "DIFF_SSTL15_T_DCI" [get_ports "DDR_DQS_n[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J2" [get_ports "DDR_DQS_n[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:450 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQS_n[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQS_n[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "DIFF_SSTL15_T_DCI" [get_ports "DDR_DQS_n[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D2" [get_ports "DDR_DQS_n[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQS_n[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQS_n[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:456 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G1" [get_ports "DDR_DQ[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G2" [get_ports "DDR_DQ[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:462 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:464 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F1" [get_ports "DDR_DQ[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:466 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:468 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F2" [get_ports "DDR_DQ[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:470 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:471 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E1" [get_ports "DDR_DQ[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:474 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:475 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E3" [get_ports "DDR_DQ[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:480 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D3" [get_ports "DDR_DQ[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:482 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y1" [get_ports "DDR_DQ[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:486 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:487 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:488 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W3" [get_ports "DDR_DQ[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:490 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:491 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:492 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B2" [get_ports "DDR_DQ[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:494 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:495 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y3" [get_ports "DDR_DQ[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:498 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:500 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:501 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W1" [get_ports "DDR_DQ[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:502 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:504 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U2" [get_ports "DDR_DQ[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:506 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:507 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA1" [get_ports "DDR_DQ[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:510 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:511 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:512 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U1" [get_ports "DDR_DQ[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:514 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:516 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA3" [get_ports "DDR_DQ[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:518 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R1" [get_ports "DDR_DQ[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:522 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:524 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M2" [get_ports "DDR_DQ[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:528 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T2" [get_ports "DDR_DQ[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:530 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:531 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R3" [get_ports "DDR_DQ[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:534 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:535 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:536 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:537 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C3" [get_ports "DDR_DQ[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:538 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:539 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:540 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:541 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T1" [get_ports "DDR_DQ[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:542 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:543 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:544 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:545 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N3" [get_ports "DDR_DQ[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:546 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:547 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T3" [get_ports "DDR_DQ[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:550 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:551 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:552 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M1" [get_ports "DDR_DQ[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:554 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:555 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:556 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K3" [get_ports "DDR_DQ[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:558 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:559 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:560 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:561 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J1" [get_ports "DDR_DQ[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:562 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:563 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:564 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:565 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K1" [get_ports "DDR_DQ[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:566 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:567 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:568 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L3" [get_ports "DDR_DQ[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:570 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:571 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:572 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:573 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L2" [get_ports "DDR_DQ[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:574 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:575 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:576 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L1" [get_ports "DDR_DQ[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:578 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:579 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:580 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DQ[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D1" [get_ports "DDR_DQ[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:582 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DQ[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:583 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DQ[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:584 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DM[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:585 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA2" [get_ports "DDR_DM[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:586 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DM[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:587 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DM[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:588 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DM[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:589 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P1" [get_ports "DDR_DM[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:590 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DM[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:591 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DM[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:592 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DM[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H3" [get_ports "DDR_DM[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:594 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DM[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:595 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DM[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:596 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15_T_DCI" [get_ports "DDR_DM[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:597 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B1" [get_ports "DDR_DM[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:598 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_DM[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:599 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "DDR_DM[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:600 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_CS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P6" [get_ports "DDR_CS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:602 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_CS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:603 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_CS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:604 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_CKE"]
set_property src_info {type:SCOPED_XDC file:1 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V3" [get_ports "DDR_CKE"]
set_property src_info {type:SCOPED_XDC file:1 line:606 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_CKE"]
set_property src_info {type:SCOPED_XDC file:1 line:607 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_CKE"]
set_property src_info {type:SCOPED_XDC file:1 line:608 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "DIFF_SSTL15" [get_ports "DDR_Clk"]
set_property src_info {type:SCOPED_XDC file:1 line:609 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N4" [get_ports "DDR_Clk"]
set_property src_info {type:SCOPED_XDC file:1 line:610 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_Clk"]
set_property src_info {type:SCOPED_XDC file:1 line:611 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "INPUT" [get_ports "DDR_Clk"]
set_property src_info {type:SCOPED_XDC file:1 line:612 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "DIFF_SSTL15" [get_ports "DDR_Clk_n"]
set_property src_info {type:SCOPED_XDC file:1 line:613 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N5" [get_ports "DDR_Clk_n"]
set_property src_info {type:SCOPED_XDC file:1 line:614 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "FAST" [get_ports "DDR_Clk_n"]
set_property src_info {type:SCOPED_XDC file:1 line:615 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "INPUT" [get_ports "DDR_Clk_n"]
set_property src_info {type:SCOPED_XDC file:1 line:616 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_CAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:617 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P3" [get_ports "DDR_CAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:618 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_CAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:619 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_CAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:620 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_BankAddr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:621 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M6" [get_ports "DDR_BankAddr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:622 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_BankAddr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:623 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_BankAddr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:624 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_BankAddr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:625 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L6" [get_ports "DDR_BankAddr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:626 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_BankAddr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:627 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_BankAddr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:628 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_BankAddr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:629 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L7" [get_ports "DDR_BankAddr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:630 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_BankAddr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:631 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_BankAddr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:632 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_Addr[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:633 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H5" [get_ports "DDR_Addr[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:634 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_Addr[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:635 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_Addr[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:636 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_Addr[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:637 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J5" [get_ports "DDR_Addr[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:638 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_Addr[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:639 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_Addr[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:640 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_Addr[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:641 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J6" [get_ports "DDR_Addr[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:642 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_Addr[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:643 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_Addr[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:644 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_Addr[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:645 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J7" [get_ports "DDR_Addr[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:646 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_Addr[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:647 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_Addr[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:648 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_Addr[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:649 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K5" [get_ports "DDR_Addr[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:650 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_Addr[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:651 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_Addr[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:652 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_Addr[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:653 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K6" [get_ports "DDR_Addr[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:654 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_Addr[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:655 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_Addr[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:656 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_Addr[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:657 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L4" [get_ports "DDR_Addr[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:658 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_Addr[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:659 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_Addr[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:660 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_Addr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:661 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K4" [get_ports "DDR_Addr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:662 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_Addr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:663 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_Addr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:664 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_Addr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:665 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M5" [get_ports "DDR_Addr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:666 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_Addr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:667 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_Addr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:668 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_Addr[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:669 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G4" [get_ports "DDR_Addr[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:670 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_Addr[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:671 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_Addr[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:672 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_Addr[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:673 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F4" [get_ports "DDR_Addr[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:674 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_Addr[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:675 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_Addr[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:676 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_Addr[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:677 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H4" [get_ports "DDR_Addr[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:678 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_Addr[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:679 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_Addr[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:680 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_Addr[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:681 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G5" [get_ports "DDR_Addr[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:682 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_Addr[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:683 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_Addr[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:684 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_Addr[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:685 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J3" [get_ports "DDR_Addr[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:686 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_Addr[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:687 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_Addr[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:688 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "SSTL15" [get_ports "DDR_Addr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:689 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M4" [get_ports "DDR_Addr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:690 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "SLOW" [get_ports "DDR_Addr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:691 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "OUTPUT" [get_ports "DDR_Addr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:693 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B5" [get_ports "PS_PORB"]
set_property src_info {type:SCOPED_XDC file:1 line:696 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "LVCMOS33" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:697 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C9" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:698 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "slow" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:699 export:INPUT save:INPUT read:READ} [current_design]
set_property drive "8" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:701 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F7" [get_ports "PS_CLK"]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9 [get_ports sysclk]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16 [get_ports {reset}]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports {cam_rst}]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports {trigger}]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F22 [get_ports {SW_camSelect}]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G22 [get_ports {SW_read_fifo}]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA9 [get_ports {cam_sysclk}]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y10 [get_ports {cam_reset}]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA11 [get_ports {cam_trigger}]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T22 [get_ports {i2c_ready}]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8 [get_ports {FIFO_DATA[7]}]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9 [get_ports {FIFO_DATA[6]}]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W10 [get_ports {FIFO_DATA[5]}]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports {FIFO_DATA[4]}]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W8 [get_ports {FIFO_DATA[3]}]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V10 [get_ports {FIFO_DATA[2]}]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W11 [get_ports {FIFO_DATA[1]}]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W12 [get_ports {FIFO_DATA[0]}]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB9 [get_ports {FIFO_OE1}]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y11 [get_ports {FIFO_RRST1}]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB10 [get_ports {FIFO_OE2}]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB11 [get_ports {FIFO_RRST2}]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports {FIFO_RCK}]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA21 [get_ports {rgb[7]}]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB21 [get_ports {rgb[6]}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA22 [get_ports {rgb[5]}]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB22 [get_ports {rgb[4]}]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB19 [get_ports {rgb[3]}]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB20 [get_ports {rgb[2]}]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y20 [get_ports {rgb[1]}]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y21 [get_ports {rgb[0]}]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA19 [get_ports {HS}]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y19 [get_ports {VS}]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F7" [get_ports "PS_CLK"]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B5" [get_ports "PS_PORB"]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "LVCMOS33" [get_ports "PS_SRSTB"]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C9" [get_ports "PS_SRSTB"]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "slow" [get_ports "PS_SRSTB"]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property drive "8" [get_ports "PS_SRSTB"]
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C12" [get_ports "MIO[53]"]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D10" [get_ports "MIO[52]"]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C10" [get_ports "MIO[51]"]
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D13" [get_ports "MIO[50]"]
set_property src_info {type:XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C14" [get_ports "MIO[49]"]
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D11" [get_ports "MIO[48]"]
set_property src_info {type:XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B10" [get_ports "MIO[47]"]
set_property src_info {type:XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D12" [get_ports "MIO[46]"]
set_property src_info {type:XDC file:2 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B9" [get_ports "MIO[45]"]
set_property src_info {type:XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E13" [get_ports "MIO[44]"]
set_property src_info {type:XDC file:2 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B11" [get_ports "MIO[43]"]
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D8" [get_ports "MIO[42]"]
set_property src_info {type:XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C8" [get_ports "MIO[41]"]
set_property src_info {type:XDC file:2 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E14" [get_ports "MIO[40]"]
set_property src_info {type:XDC file:2 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C13" [get_ports "MIO[39]"]
set_property src_info {type:XDC file:2 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F13" [get_ports "MIO[38]"]
set_property src_info {type:XDC file:2 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B14" [get_ports "MIO[37]"]
set_property src_info {type:XDC file:2 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A9" [get_ports "MIO[36]"]
set_property src_info {type:XDC file:2 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F14" [get_ports "MIO[35]"]
set_property src_info {type:XDC file:2 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B12" [get_ports "MIO[34]"]
set_property src_info {type:XDC file:2 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G13" [get_ports "MIO[33]"]
set_property src_info {type:XDC file:2 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C7" [get_ports "MIO[32]"]
set_property src_info {type:XDC file:2 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F9" [get_ports "MIO[31]"]
set_property src_info {type:XDC file:2 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A11" [get_ports "MIO[30]"]
set_property src_info {type:XDC file:2 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E8" [get_ports "MIO[29]"]
set_property src_info {type:XDC file:2 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A12" [get_ports "MIO[28]"]
set_property src_info {type:XDC file:2 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D7" [get_ports "MIO[27]"]
set_property src_info {type:XDC file:2 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A13" [get_ports "MIO[26]"]
set_property src_info {type:XDC file:2 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F12" [get_ports "MIO[25]"]
set_property src_info {type:XDC file:2 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B7" [get_ports "MIO[24]"]
set_property src_info {type:XDC file:2 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E11" [get_ports "MIO[23]"]
set_property src_info {type:XDC file:2 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A14" [get_ports "MIO[22]"]
set_property src_info {type:XDC file:2 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F11" [get_ports "MIO[21]"]
set_property src_info {type:XDC file:2 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A8" [get_ports "MIO[20]"]
set_property src_info {type:XDC file:2 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E10" [get_ports "MIO[19]"]
set_property src_info {type:XDC file:2 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A7" [get_ports "MIO[18]"]
set_property src_info {type:XDC file:2 line:356 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E9" [get_ports "MIO[17]"]
set_property src_info {type:XDC file:2 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D6" [get_ports "MIO[16]"]
set_property src_info {type:XDC file:2 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E6" [get_ports "MIO[15]"]
set_property src_info {type:XDC file:2 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B6" [get_ports "MIO[14]"]
set_property src_info {type:XDC file:2 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A6" [get_ports "MIO[13]"]
set_property src_info {type:XDC file:2 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C5" [get_ports "MIO[12]"]
set_property src_info {type:XDC file:2 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B4" [get_ports "MIO[11]"]
set_property src_info {type:XDC file:2 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G7" [get_ports "MIO[10]"]
set_property src_info {type:XDC file:2 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C4" [get_ports "MIO[9]"]
set_property src_info {type:XDC file:2 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E5" [get_ports "MIO[8]"]
set_property src_info {type:XDC file:2 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D5" [get_ports "MIO[7]"]
set_property src_info {type:XDC file:2 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A4" [get_ports "MIO[6]"]
set_property src_info {type:XDC file:2 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A3" [get_ports "MIO[5]"]
set_property src_info {type:XDC file:2 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E4" [get_ports "MIO[4]"]
set_property src_info {type:XDC file:2 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F6" [get_ports "MIO[3]"]
set_property src_info {type:XDC file:2 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A2" [get_ports "MIO[2]"]
set_property src_info {type:XDC file:2 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A1" [get_ports "MIO[1]"]
set_property src_info {type:XDC file:2 line:468 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G6" [get_ports "MIO[0]"]
