# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/georges/Documents/GitHub/MQP/ZedFinalCams/ZedFinalCams.srcs/sources_1/ip/line_bram/line_bram.xci
# IP: The module: 'line_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/georges/Documents/GitHub/MQP/ZedFinalCams/ZedFinalCams.srcs/sources_1/ip/line_bram/line_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'line_bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/georges/Documents/GitHub/MQP/ZedFinalCams/ZedFinalCams.srcs/sources_1/ip/line_bram/line_bram.xci
# IP: The module: 'line_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/georges/Documents/GitHub/MQP/ZedFinalCams/ZedFinalCams.srcs/sources_1/ip/line_bram/line_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'line_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
