# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.cache/wt [current_project]
set_property parent.project_path C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths c:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.srcs [current_project]
add_files C:/Users/John/Desktop/MQP/backups/coord1.coe
add_files C:/Users/John/Desktop/MQP/backups/coord2.coe
add_files C:/Users/John/Desktop/MQP/backups/vga_map.coe
add_files -quiet C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.runs/processing_system7_0_synth_1/processing_system7_0.dcp
set_property used_in_implementation false [get_files C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.runs/processing_system7_0_synth_1/processing_system7_0.dcp]
add_files -quiet C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
add_files -quiet C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp]
add_files -quiet C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.runs/blk_mem_gen_1_synth_1/blk_mem_gen_1.dcp
set_property used_in_implementation false [get_files C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.runs/blk_mem_gen_1_synth_1/blk_mem_gen_1.dcp]
add_files -quiet C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.runs/blk_mem_gen_2_synth_1/blk_mem_gen_2.dcp
set_property used_in_implementation false [get_files C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.runs/blk_mem_gen_2_synth_1/blk_mem_gen_2.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.srcs/sources_1/new/rangefinder.v
  C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.srcs/sources_1/new/mqp_top.v
}
read_vhdl -library xil_defaultlib C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.srcs/sources_1/new/vga_controller_640_60.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.srcs/constrs_1/new/mqp.xdc
set_property used_in_implementation false [get_files C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.srcs/constrs_1/new/mqp.xdc]


synth_design -top mqp_top -part xc7z020clg484-1


write_checkpoint -force -noxdef mqp_top.dcp

catch { report_utilization -file mqp_top_utilization_synth.rpt -pb mqp_top_utilization_synth.pb }
