# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/georges/Documents/GitHub/MQP/ZedFinalCams/ZedFinalCams.srcs/sources_1/ip/blk_mem_640_480/blk_mem_640_480.xci
# IP: The module: 'blk_mem_640_480' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/georges/Documents/GitHub/MQP/ZedFinalCams/ZedFinalCams.srcs/sources_1/ip/blk_mem_640_480/blk_mem_640_480_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_640_480'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/georges/Documents/GitHub/MQP/ZedFinalCams/ZedFinalCams.srcs/sources_1/ip/blk_mem_640_480/blk_mem_640_480.xci
# IP: The module: 'blk_mem_640_480' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/georges/Documents/GitHub/MQP/ZedFinalCams/ZedFinalCams.srcs/sources_1/ip/blk_mem_640_480/blk_mem_640_480_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_640_480'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
