# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/John/Documents/GitHub/MQP/mapping/mapping.srcs/sources_1/ip/dcm_96M/dcm_96M.xci
# IP: The module: 'dcm_96M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/John/Documents/GitHub/MQP/mapping/mapping.srcs/sources_1/ip/dcm_96M/dcm_96M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_96M'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/John/Documents/GitHub/MQP/mapping/mapping.srcs/sources_1/ip/dcm_96M/dcm_96M.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_96M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/John/Documents/GitHub/MQP/mapping/mapping.srcs/sources_1/ip/dcm_96M/dcm_96M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_96M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/John/Documents/GitHub/MQP/mapping/mapping.srcs/sources_1/ip/dcm_96M/dcm_96M.xci
# IP: The module: 'dcm_96M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/John/Documents/GitHub/MQP/mapping/mapping.srcs/sources_1/ip/dcm_96M/dcm_96M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_96M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/John/Documents/GitHub/MQP/mapping/mapping.srcs/sources_1/ip/dcm_96M/dcm_96M.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_96M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/John/Documents/GitHub/MQP/mapping/mapping.srcs/sources_1/ip/dcm_96M/dcm_96M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_96M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
