webtalk_init -webtalk_dir C:\\Users\\John\\Documents\\GitHub\\MQP\\project_2\\project_2.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Sep 27 13:17:26 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "u40bi0fkbp0kitqn2phir7flc4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1474914350710" -context "sdk\\\\bsp/1474914350710"
webtalk_add_data -client sdk -key hwid -value "1473212510378" -context "sdk\\\\bsp/1474914350710"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1474914350710"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1474914350710"
webtalk_add_data -client sdk -key uid -value "1474914359716" -context "sdk\\\\application/1474914359716"
webtalk_add_data -client sdk -key hwid -value "1473212510378" -context "sdk\\\\application/1474914359716"
webtalk_add_data -client sdk -key bspid -value "1474914350710" -context "sdk\\\\application/1474914359716"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1474914359716"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1474914359716"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1474914359716"
webtalk_add_data -client sdk -key uid -value "1474914724744" -context "sdk\\\\bsp/1474914724744"
webtalk_add_data -client sdk -key hwid -value "1473212510378" -context "sdk\\\\bsp/1474914724744"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1474914724744"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1474914724744"
webtalk_add_data -client sdk -key uid -value "1474914727149" -context "sdk\\\\application/1474914727149"
webtalk_add_data -client sdk -key hwid -value "1473212510378" -context "sdk\\\\application/1474914727149"
webtalk_add_data -client sdk -key bspid -value "1474914724744" -context "sdk\\\\application/1474914727149"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1474914727149"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1474914727149"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1474914727149"
webtalk_transmit -clientid 1224792401 -regid "" -xml C:\\Users\\John\\Documents\\GitHub\\MQP\\project_2\\project_2.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\John\\Documents\\GitHub\\MQP\\project_2\\project_2.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\John\\Documents\\GitHub\\MQP\\project_2\\project_2.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
