webtalk_init -webtalk_dir C:\\Users\\John\\Documents\\GitHub\\MQP\\project_2\\project_2.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Sep 12 11:25:53 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "sepjbrnscpegp8klmi7qthdgba" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1473693733130" -context "sdk\\\\bsp/1473693733130"
webtalk_add_data -client sdk -key hwid -value "1473212510378" -context "sdk\\\\bsp/1473693733130"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1473693733130"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1473693733130"
webtalk_transmit -clientid 1297220417 -regid "" -xml C:\\Users\\John\\Documents\\GitHub\\MQP\\project_2\\project_2.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\John\\Documents\\GitHub\\MQP\\project_2\\project_2.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\John\\Documents\\GitHub\\MQP\\project_2\\project_2.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
