# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.srcs/sources_1/ip/processing_system7_0/processing_system7_0.xci
# IP: The module: 'processing_system7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.srcs/sources_1/ip/processing_system7_0/processing_system7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'processing_system7_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.srcs/sources_1/ip/processing_system7_0/processing_system7_0.xci
# IP: The module: 'processing_system7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/John/Documents/GitHub/MQP/mqp_test/mqp_test.srcs/sources_1/ip/processing_system7_0/processing_system7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'processing_system7_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
