webtalk_init -webtalk_dir C:\\Users\\georges\\Documents\\GitHub\\MQP\\ZedCamTest\\ZedCamTest.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Nov 3 11:27:51 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "tucs02pj0q49k2hltfi6gm422e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1478136034625" -context "sdk\\\\hardware/1478136034625"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1478136034625"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1478136034625"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.2" -context "sdk\\\\hardware/1478136034625"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1478136034625"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1478136034625"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1478136034625"
webtalk_add_data -client sdk -key uid -value "1478136755987" -context "sdk\\\\bsp/1478136755987"
webtalk_add_data -client sdk -key hwid -value "1478136034625" -context "sdk\\\\bsp/1478136755987"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1478136755987"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1478136755987"
webtalk_add_data -client sdk -key uid -value "1478136762897" -context "sdk\\\\application/1478136762897"
webtalk_add_data -client sdk -key hwid -value "1478136034625" -context "sdk\\\\application/1478136762897"
webtalk_add_data -client sdk -key bspid -value "1478136755987" -context "sdk\\\\application/1478136762897"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1478136762897"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1478136762897"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1478136762897"
webtalk_transmit -clientid 835659259 -regid "" -xml C:\\Users\\georges\\Documents\\GitHub\\MQP\\ZedCamTest\\ZedCamTest.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\georges\\Documents\\GitHub\\MQP\\ZedCamTest\\ZedCamTest.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\georges\\Documents\\GitHub\\MQP\\ZedCamTest\\ZedCamTest.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
