
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.1 EDK_P.15xf
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Configurations for Standalone BSP
*
*******************************************************************/

#define MICROBLAZE_PVR_NONE
